//This file was generated by script mkregs.py

//register address mapping
#define KNN_RESET 0
#define KNN_START 1
#define KNN_VALID_IN 2
#define KNN_TEST_PT 3
#define KNN_DATA_PT 4
#define KNN_SAMPLE 5
#define KNN_ADDR 6
#define KNN_VALID_OUT 7
#define KNN_ADD 8
